### ISSUE TITLE
[Feature Request] settings.db API

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#10]
> This is not a must have and i don't expect this to happen any time soon but please keep it on your to-do list.

Functions i would like to see resulting from this are:

```python
ts3db.getCurrentLanguage()
ts3db.isPluginEnabled(string PluginName)
ts3db.getCurrentStyle()
ts3db.getCurrentIconPack()
ts3db.getCurrentSoundPack()
ts3db.getLastConnection() #which returns a list with all the values (LastUsedServerNickName etc.)
ts3db.getContacts() #correctly formatted as tuple
ts3db.checkContactStatus(uid) #which returns 0,1,2 (1 is blocked for example)
ts3db.purgeContacts(int status) #0-2
ts3db.clearContacts() #completely clears contacts table (should require GUI confirmation)
ts3db.clearBookmarks() #completely bookmarks contacts table (should require GUI confirmation)
ts3db.clearIdentities() #completely clears ID's table (should require GUI confirmation)
#ts3db.setLastBan(int LastBanTime, string LastBanReason) #?prepares the ban window for use with plugins
ts3db.setNews(string NewsText, bool NewsClosed)
ts3db.getBanPresets()
ts3db.getAFKPresets()
ts3db.getCaptureProfiles()
ts3db.getPlaybackProfiles()
ts3db.isSyncing()
ts3db.getChatFont()
```

**Comment by svenpaulsen** [comment]
I'd prefer not having an unofficial API for database access in pyTSon. Instead, this kind of functionality should be implemented in the official TeamSpeak plugin SDK.

**Comment by pathmann** [comment]
Same here.

I could imagine to deliver some convenience API/class which offers readonly (!) access to the settings.db.
Write access or anything else playing with sqlite databases (see other issues) won't be implemented by me (settings in sqlite ... pah).

**Comment by Bluscream** [comment]
Then just think away the write functions ^~^

**Comment by pathmann** [comment]
I started coding some function and ended in a basic function, which returns all data from a table. 
I don't want to go further (eg. parsing values), because if the database structure changes, I have to adapt.

So long story short: I decided not to add anything about the settings (as long as the official sdk does not support it).

But here is an example, of how to read from the config with current ressources: https://github.com/pathmann/pyTSon_plugins/blob/master/scripts/answercontacts.py
