### ISSUE TITLE
Downloaded Custom Badges and broke my PyTSon

### ISSUE THREAD

**Issue by itseyup** [pathmann/pyTSon#128]
Hi, I downloaded Custom Badges today. And whenever i want to open my TeamSpeak3, It opens a command prompt named "python.exe" and it closes. Than another one opens. It happen's like 4-5 minutes. When TeamSpeak3 launches, My scripts is less. I had like 70 scripts on global menu, now i don't even have half. Please help ASAP!, Here is a example CTRL+L ScreenShot:
![Screenshot_1](https://user-images.githubusercontent.com/78562624/131389561-06cc7a63-25a8-4c44-8482-c7bcc8a16b1f.png)

**Comment by pathmann** [comment]
Some of your scripts depend on psutil.

Install this dependency in the settings and you should be fine.

**Comment by itseyup** [comment]
Sorry for late reply but how can I install this? I installed it on cmd by pip install psutil, I thought it installed but still gaves me this error.

**Comment by pathmann** [comment]
If you mean a command line like bash or anything else, you are installing psutil in your regular python environment.
pyTSon runs in a complete separated environment. You can of course use the pyTSon console to invoke pip in pyTSon's own environment.

But in pyTSon's settings there is an area where you can add and remove site packages. This is where you can easily install your site packages (like psutil).


P.S.: Because I rarely use TeamSpeak nowadays and I've (some kind of accidentally) updated my client some time ago, I have no pyTSon available right now, so my answer might be a bit inaccurate.
