### ISSUE TITLE
how to create separate thread in plugin

### ISSUE THREAD

**Issue by MEXAHOTABOP** [pathmann/pyTSon#3]
in C plugins i can create separate thread where i can do some while true stuff
how can i do something like this in pyTSon?
multiprocessing module without join() kill procces when main thread exit with join() ts3 main thread locked up

real use case
i need parse log file and play sound in ts3 every time when string found

**Comment by pathmann** [comment]
In fact, you can't. You have to create a C plugin for this task (if you can't find that string with any client callback?).

Multithreading is currently not implemented (in both ways: you can't use python's threading module for example, and events from the client, which are fired from other threads than the main thread are not handled).

I'm not sure, if this can be changed or if this will be changed by me.

**Comment by MEXAHOTABOP** [comment]
in docs i cant find callback what can be called every 0.5 sec
and any heavy code cant be executed in callback because its lock main thread

**Comment by pathmann** [comment]
If the log you are parsing is teamspeak related, chances are high, you get the string you are searching for in an event.

**Comment by pathmann** [comment]
I thought a bit about multithreading in pyTSon. My result is, that you can either have multithreading support (user threading, sound processing callbacks, etc.) or PythonQt, because if you have multithreading support, you have to make sure, that processing some gui functionality runs in the specific thread.
And I here like PythonQt support more for pyTSon. If you really need multithreading support, a c plugin should be the tool of your choice.

Closed. (If you know a way to work around this, feel free to commit some changes or contact me.)
