### ISSUE TITLE
sendFile not working?

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#39]
```python
    def uploadAvatar(self, schid, image):
        try:
            (error, ownID) = ts3lib.getClientID(schid)
            (error, ownUID) = ts3lib.getClientVariableAsString(schid, ownID, ts3defines.ClientProperties.CLIENT_UNIQUE_IDENTIFIER)
            from base64 import b64encode
            ownUID = ownUID.encode('ascii')
            filename = "avatar_"+b64encode(ownUID).decode("ascii").split('=')[0]
            ts3lib.printMessageToCurrentTab(str(filename))
            (error, ftid) = ts3lib.sendFile(schid, 0, "", "/avatar", 1, 0, image);
            print("Started file transfer #"+str(ftid)+" with error code: "+str(error))
        except:
            try: from traceback import format_exc;ts3lib.logMessage(format_exc(), ts3defines.LogLevel.LogLevel_ERROR, "PyTSon Script", 0)
            except:
                try: from traceback import format_exc;print(format_exc())
                except: print("Unknown Error")
```
doesn't seem to work for me. I can't give additional infos cause https://github.com/pathmann/pyTSon/blob/master/tools/generator/generate_src.py#L28

**Comment by pathmann** [comment]
> doesn't seem to work for me. I can't give additional infos cause 
What does that mean exactly? Is any exception thrown? What is the output of your prints? Is a new file created (but maybe empty)?

**Comment by Bluscream** [comment]
Nothing is being created and nothing is printed anywhere except ``` 1/16/2017 16:19:04	ClientUI	Info	Calling plugin onMenuItemEvent: scHandlerID=1type=0, menuItemID=6, selectedItemID=0 ```

**Comment by pathmann** [comment]
There are two unconditional prints (one to current tab, the other to stdout: Started file transfer ...).
So if nothing is printed anywhere, you either don't receive any output in stdout and there is propably an exception before the printMessageToCurrentTab or your function is not called at all and the problem is hiding somewhere else.

**Comment by Bluscream** [comment]
That's what I assumed to. but since my ultimate try catch I should atleast get "Unkown Error" when something fails somewhere which I don't get.

**Comment by pathmann** [comment]
I think your parameters are simply wrong.

> @param file: the complete path to the file in the channel
@param sourceDirectory: the directory on the system, where the original file is placed in

So in your case, file has to be set to "/avatar/" + filename and sourceDirectory os.dirname(os.path.abspath(image)) (if image is a path to the image). But this will also not work, because the local file and the new remote have the same filename. You can workaround this by calling ts3lib.requestRenameFile, which is the hard way, because the filetransfer status event is indeed not triggered (by choice). So rename your local file first, then upload.

Keep in mind, that I didn't designed this functions and pyTSon does not manipulate any parameters. All functions are simply ported from C to python.

Maybe I'm wrong and there is a way without renaming, feel free to play around with both paremeters.

This is working for me (tested with the current master):
```python
from ts3plugin import ts3plugin

import ts3lib, pytson
from ts3defines import ERROR_ok

class sendfiletest(ts3plugin):
    name = "sendfiletest"
    apiVersion = 21
    offersConfigure = False
    requestAutoload = False
    version = "0.0a"
    author = "Thomas \"PLuS\" Pathmann"
    description = "Test sendfile"
    offersConfigure = False
    commandKeyword = "sendfile"
    infoTitle = None
    menuItems = []
    hotkeys = []

    def __init__(self):
        self.retcode = None

    def processCommand(self, schid, command):
        if command == "test":
            err, myid = ts3lib.getClientID(schid)
            if err == ERROR_ok:
                err, curchan = ts3lib.getChannelOfClient(schid, myid)
                if err == ERROR_ok:
                    self.retcode = ts3lib.createReturnCode()
                    ts3lib.sendFile(schid, curchan, "", "/pyTSon.conf", True, False, pytson.getConfigPath() + "/", self.retcode)
                    return True

        return False

    def onServerErrorEvent(self, schid, errorMessage, error, returnCode, extraMessage):
        if self.retcode == returnCode:
            print("servererror %s %s %s %s" % (schid, errorMessage, error, extraMessage))
            return True

        return False
```

**Comment by Bluscream** [comment]
this makes no sense lol 

```
1/18/2017 00:47:40	pyTSon.PluginHost.init	Error	Error loading python plugin from C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon\scripts\dynamicAvatar\: Traceback (most recent call last):
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\ts3plugin.py", line 209, in reload
    cls.modules[base] = importlib.__import__(base)
  File "<frozen importlib._bootstrap>", line 1055, in __import__
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:/Users/blusc/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\dynamicAvatar\__init__.py", line 3, in <module>
    from os import path, dirname
ImportError: cannot import name 'dirname'
```

**Comment by Bluscream** [comment]
This shit is getting a lot more complicated then I expected but it works now, thanks :)
