### ISSUE TITLE
Realign general section of ConfigDialog a bit

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#55]
![image](https://cloud.githubusercontent.com/assets/3318223/24609043/738586ce-1879-11e7-8881-adf7f74453de.png)
Also as a tip: If you use a checkable group instead of a checkbox and move the combobox in the group then it toggles automatically :)
I'd do it myself but i don't have Qt installed currently :c

**Comment by Bluscream** [comment]
Also as a tip: If you use a group instead of a checkbox and move the combobox in the group the it gets automatically enabled/disabled :)

**Comment by pathmann** [comment]
Two arrows painted on a screeenshot as description? Really? From now on, I'll close every issue immediately, if no description is given at all! The title is a title, not a description. 

Thx for the tip, I'm using Qt since 4.0. GroupBoxes have titles, so long titles (as like whole sentences) are imho ugly and a bad choice.

**Comment by Bluscream** [comment]
I'm downloading QtCreator and making a PR instead then :)
