### ISSUE TITLE
Send plugin commands the old way

### ISSUE THREAD

**Issue by Bluscream** [pathmann/pyTSon#75]
Is there a way to send a plugin cmd the unencrypted way?
currently
```py
ts3lib.sendPluginCommand(schid, command, ts3defines.PluginMessageTarget.PLUGIN_MESSAGE_TARGET_SERVER, None)
```
results in 

```
[OUT] plugincmd name=pyTSon data=1\sA*QJ\s86\s78\s1\s1\shi\sKrvP1+g2PkuKFvDj8ZxIfVwRz0o4NhNmg6Aa\/B0vVO5R8KNW4ewVspbi9\/ppq6mpqdU7BVZj4n768QHi4hXJP8ySJXsJfLdRZ+TToFebe6JSO9YscS4Bm15n9Q4Ri5u6MNkqV31IheIY\/lHriHDMcMqpF6XiOhA= targetmode=2 target=78
```

**Comment by pathmann** [comment]
In theory, you can use the sendPluginCommand function of the _ts3lib module, which would use the "raw" SDK function.
The receiving part is more tricky, because the event is not handled the standard way: The onPluginCommandEvent is fired into the PluginHost (like any other event) but then delivered to the PluginCommandHandler (and not to each plugin). If the PluginCommandHandler handled the event (a plugincommand might be splitted up in multiple parts), the complete command is delvivered to each plugin (and callbackproxy).

**Comment by Bluscream** [comment]
Would i just `from _ts3lib import sendPluginCommand`?

**Comment by pathmann** [comment]
> Would i just from _ts3lib import sendPluginCommand?
Untested, but yes, that should work.

That would end in pyTSon returning and error on load aka. this will break everything.

**Comment by Bluscream** [comment]
Ah okay thanks for the info. Maybe provide a `onRawPluginCommand` for these cases, thanks <3

**Comment by pathmann** [comment]
Why? The only drawback is a little timeshift for the first command sent in any new "conversation" (to exchange keys). After that there is only a little overhead if the commands are splitted and the identity check of each command.
